# Docker compose for the CRM database
# Alexandre HAMON, Mathis RACINNE-DIVET, Gurvan RENAULT, Margaux SCHNELZAUER-HENRY
version: '3.3'
services:
  database:
    image: mysql:8.0
    restart: always
    ports:
      # port de la machine:port du conteneur
      - '63306:53306'
    expose:
      # Ouvre le port 53306 sur le conteneur
      - '53306'
    volumes:
      # Donnees hote:donnees sur le fs du container
      - ./database/data:/var/lib/mysql
      - ./database/config:/etc/mysql/conf.d